# Generated by Django 4.2.11 on 2025-09-22 15:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Баланс",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Создан",
                        ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Обновлен",
                        ),
                ),
            ],
            options={
                "verbose_name": "Счет",
                "verbose_name_plural": "Счета",
            },
        ),
        migrations.CreateModel(
            name="WalletOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Пополнение"),
                            ("WITHDRAW", "Списание"),
                            ],
                        max_length=10,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Сумма операции",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="wallet.wallet",
                        verbose_name="Счет",
                    ),
                ),
            ],
            options={
                "verbose_name": ("Операция",),
                "verbose_name_plural": "Операции",
            },
        ),
    ]
